### ISSUE TITLE
FileNotFound Error when examing

### ISSUE THREAD

**Issue by Del0s1on** [BSDFZ-programming-team/MalPro#1]
When I'm examing with the default model, an error occurred.

```
Traceback (most recent call last):
  File "D:\MALPRO\MalPro\main.py", line 82, in <module>
    result = process_upload_asm(file_location)
  File "D:\MALPRO\MalPro\main.py", line 24, in process_upload_asm
    copyfile('3gramfeature.csv', './model/3gramfeature_fitting_use.csv')
  File "c:\Users\1\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '3gramfeature.csv'
```

I'm using python3.9.0 and all the versions are currect.

**Comment by LamentXU123** [comment]
Hi
So sorry to hear this. This error happens when examing because we FORGOT to upload 3gramfeature.csv so a filenotfound error will occur when the program intend to copy .3gramfeature.csv to model.
I will fix it immediately. We decide to put the .csv file in /model and delete the copying features.
So sorry to cause such a trouble. plz wait for the next update which is coming soon

**Comment by LamentXU123** [comment]
Now the code works

**Comment by LamentXU123** [comment]
> Hi
> So sorry to hear this. This error happens when examing because we FORGOT to upload 3gramfeature.csv so a filenotfound error will occur when the program intend to copy .3gramfeature.csv to model.
> I will fix it immediately. We decide to put the .csv file in /model and delete the copying features.
> So sorry for making such a trouble to you. plz wait for the next update which is coming soon 
>
